export const API_BASE_URL = 'http://127.0.0.1:8787';

export const API_ENDPOINTS = {
  VAULT: {
    OPEN: `${API_BASE_URL}/vault/open`,
    FILES: `${API_BASE_URL}/vault/files`,
    FOLDERS: `${API_BASE_URL}/vault/folders`,
    FILE: `${API_BASE_URL}/vault/file`,
    RENAME: `${API_BASE_URL}/vault/file/rename`,
    TRASH: `${API_BASE_URL}/vault/trash`,
    RESTORE: `${API_BASE_URL}/vault/trash/restore`,
    EMPTY_TRASH: `${API_BASE_URL}/vault/trash/empty`,
  },
  TODOS: `${API_BASE_URL}/todos`,
  GITHUB: {
    CHECK_GIT: `${API_BASE_URL}/github/check-git`,
    VALIDATE_TOKEN: `${API_BASE_URL}/github/validate-token`,
    REPOS: `${API_BASE_URL}/github/repos`,
    CLONE: `${API_BASE_URL}/github/clone`,
    REPO_FILES: `${API_BASE_URL}/github/repo/files`,
    SAVE_FILE: `${API_BASE_URL}/github/repo/save-file`,
    CREATE_FILE: `${API_BASE_URL}/github/repo/create-file`,
    DELETE_FILE: `${API_BASE_URL}/github/repo/delete-file`,
    RENAME_FILE: `${API_BASE_URL}/github/repo/rename-file`,
    RENAME_FOLDER: `${API_BASE_URL}/github/repo/rename-folder`,
    CREATE_FOLDER: `${API_BASE_URL}/github/repo/create-folder`,
    STATUS: `${API_BASE_URL}/github/status`,
    PULL: `${API_BASE_URL}/github/pull`,
    PUSH: `${API_BASE_URL}/github/push`,
    TRASH: `${API_BASE_URL}/github/repo/trash`,
    RESTORE_TRASH: `${API_BASE_URL}/github/repo/trash/restore`,
    EMPTY_TRASH: `${API_BASE_URL}/github/repo/trash/empty`,
  },
  AI: {
    SUMMARIZE: `${API_BASE_URL}/ai/summarize`,
    TRANSLATE: `${API_BASE_URL}/ai/translate`,
    IMPROVE: `${API_BASE_URL}/ai/improve`,
    EXPAND: `${API_BASE_URL}/ai/expand`,
    SHORTEN: `${API_BASE_URL}/ai/shorten`,
    PROOFREAD: `${API_BASE_URL}/ai/proofread`,
    STREAM: `${API_BASE_URL}/ai/stream`,
    EXTRACT: `${API_BASE_URL}/ai/extract`,
    EXTRACT_URL: `${API_BASE_URL}/ai/extract-url`,
    SETTINGS: `${API_BASE_URL}/ai/settings`,
  },
  OCR: {
    STATUS: `${API_BASE_URL}/ocr/status`,
    SETTINGS: `${API_BASE_URL}/ocr/settings`,
    EXTRACT: `${API_BASE_URL}/ocr/extract`,
  },
  GRAPH: {
    NOTE_INFO: `${API_BASE_URL}/graph/note-info`,
    LOCK_NOTE: `${API_BASE_URL}/graph/lock-note`,
  },
  MCP: {
    SERVERS: `${API_BASE_URL}/mcp/servers`,
    TOOLS: `${API_BASE_URL}/mcp/tools`,
    TOOLS_CALL: `${API_BASE_URL}/mcp/tools/call`,
  },
} as const;
